---
title: "Variable B1 and P6"
author: "Cal Chengqi Fang"
date: "3/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
library(tidyverse)
library(knitr)

setwd("~/Box Sync/CCSSBP Project")
# Read in the dataset
gp_describe <- readRDS("data/gp_describe.rds")
```

The three distribution tables are as follows:       

```{r, warning=FALSE, message=FALSE, echo=FALSE}
gp_describe$gender <- as.factor(gp_describe$gender)
levels(gp_describe$gender) <- c("Female", "Male")
table(gp_describe$gender) %>% 
  kable(col.names = c("Biological Gender", "Frequency"),
        caption = "the Distribution of Biological Gender")
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
gp_describe$seorient <- as.factor(gp_describe$seorient)
levels(gp_describe$seorient) <- c("Heterosexual", "Homosexual", "Bisexual", "Pansexual", "Asexual", "Others", "Unsure")
table(gp_describe$seorient) %>% 
  kable(col.names = c("Sexual Orientation", "Frequency"),
        caption = "the Distribution of Sexual Orientation")
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
table(gp_describe$gender, gp_describe$seorient) %>% 
  kable(caption = "the Cross-distribution of Biological Gender")
```
